language: node_js
node_js:
- '4.2'
- '5'
matrix:
  allow_failures:
  - node_js: '5'
sudo: false
env:
  global:
  - CXX=g++-4.8
  - NODE_ENV=test
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
