#!/bin/bash
#
#       /etc/rc.d/init.d/filibuster
#
#       provide nsenter into container
#       # Author anandkumarpatel
#       ##                 #
#
# chkconfig:   2345 95 95
# description: Daemon for docker.io

### BEGIN INIT INFO
# Provides:       filibuster
# Required-Start: $network docker
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start: 2 3 4 5
# Default-Stop:  0 1 6
# Short-Description: start and stop filibuster
# Description: Filibuster
### END INIT INFO

# Source function library.
. /etc/init.d/functions

# program env's
export NODE_ENV=default

prog="filibuster"
rootPath="/root/Filibuster"
npm="/usr/local/bin/npm"
pidfile="/var/run/$prog.pid"
lockfile="/var/lock/subsys/$prog"
logfile="/var/log/$prog"

prestart() {
    cd $rootPath
    $npm install
}

start() {
    echo -n "Starting filibuster: "
    cd $rootPath
    $npm start &> $logfile &
    echo $! > $pidfile
    touch $lockfile
    return 0
}

stop() {
    echo -n $"Stopping $prog: "
    kill $pidfile
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

case "$1" in
    start)
        prestart
        start
        ;;
    stop)
        stop
        ;;
    status)
        status -p $pidfile $prog
        ;;
    restart)
        stop
        start
        ;;
    update)
        stop
        prestart
        start
        ;;
    *)
        echo "Usage: filibuster {start|stop|status|restart|update}"
        exit 1
esac

exit $?